
############################ Default configuration #########################
baseURL = 'https://careonline.github.io'
languageCode = 'en-us'
title = 'CARE AI | UTSA'

# post pagination
paginate = "5"
# post excerpt
summaryLength = "5"


[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugings ######################################

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"


########################### Navigation ###################################

# main menu

[[menu.main]]
URL = "research/"
name = "research"
weight = 1


# footer menu
[[menu.footer]]
URL = "https://www.google.com/maps/place/UTSA+School+of+Data+Science/@29.4237929,-98.4985696,17z/data=!3m1!4b1!4m6!3m5!1s0x865c5959d6ecd219:0x32bcb346e162c044!8m2!3d29.4237929!4d-98.4959947!16s%2Fg%2F11k4p0b572?entry=ttu"
name = "Visit CARE AI at San Pedro I 262, 506 Dolorosa St, San Antonio, TX 78204"
weight = 1



######################### Default Parameters ###########################
[params]
# home
home = "Home"
# logo
logo = "images/long_logo.svg"

# meta data
author = "Ke Yang"
description = "This is the website of CARE AI at UTSA."

# copyright
copyright = "&copy;2023 The University of Texas at San Antonio"

# footer menu
footertext = "Visit CARE AI at San Pedro I 262"

footeraddr = "506 Dolorosa St, San Antonio, TX 78204"

footerURL = "https://www.google.com/maps/place/UTSA+School+of+Data+Science/@29.4237929,-98.4985696,17z/data=!3m1!4b1!4m6!3m5!1s0x865c5959d6ecd219:0x32bcb346e162c044!8m2!3d29.4237929!4d-98.4959947!16s%2Fg%2F11k4p0b572?entry=ttu"



# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format


# cookies
[params.cookies]
enable = true
expire_days = 2


####################### bheader #######################################
[params.bheader]
image = "images/bheader_logo.svg"
logourl = "https://www.utsa.edu"

####################### bfooter #######################################
[params.bfooter]
image = "images/bfooter_logo.svg"
logourl = "https://www.utsa.edu"


####################### banner #######################################
[params.banner]
bgImage = "images/banner/web_banner.svg"
title = "We aim at promoting AI responsibility."
image = "images/banner/web_focus.svg"


######################## focus area ###############################
[params.focus]
enable = true

######################## team ###############################
[params.team]
enable = true
title = "Team"

######################## Ads ###############################
[params.ad]
enable = true
image = "images/i_ad.svg"
title = "This could be you!"
description = "We are always looking for people who are passionate about advancing AI responsibility. You can get in touch with us by using one of the following methods."
contactlink = "mailto:ke.yang@utsa.edu"
formlink = "https://forms.gle/S7faZMDaysXiu9kJA"

############################## Social Site ##########################
[[params.social]]
icon = "ti-email"
link = "mailto:ke.yang@utsa.edu"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/careonline"

############################## Footer Policy ##########################
[[params.policy]]
name = "Policies"
link = "https://www.utsa.edu/policies/"
[[params.policy]]
name = "Web Accessibility"
link = "https://utsa.edu/policies/accessibility"
[[params.policy]]
name = "Required Links"
link = "https://utsa.edu/policies/reqlinks.html"
[[params.policy]]
name = "UT System"
link = "https://utsystem.edu/"



